services:
  gateway:
    image: nginx
    restart: unless-stopped
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./app/public:/var/www/public
    networks:
      - products

  app:
    build:
      context: ./app
      target: server
    restart: unless-stopped
    volumes:
      - ./app/public:/var/www/public
    env_file:
      ./app/.env.app
    networks:
      - products
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_DATABASE}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - products
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  products:
    driver: bridge

volumes:
  db_data: